# Data analysis

In [1]:
import contextlib
import pandas as pd
import polars as pl
from tqdm import tqdm

# Loading the data

In [63]:
df = pl.read_parquet("df_gliner_full.parquet").unnest("res").explode("titulaire-nom-positions")
df.select(pl.selectors.by_name("titulaire-nom","titulaire-nom-positions","person","entities","political ideology"))

shape: (9_010, 6)
┌───────────────┬───────────────┬──────────────────┬─────────────────┬─────────────────┬───────────┐
│ titulaire-nom ┆ contexte-tour ┆ titulaire-nom-po ┆ person          ┆ entities        ┆ political │
│ ---           ┆ ---           ┆ sitions          ┆ ---             ┆ ---             ┆ ideology  │
│ str           ┆ i64           ┆ ---              ┆ list[struct[2]] ┆ struct[7]       ┆ ---       │
│               ┆               ┆ i64              ┆                 ┆                 ┆ str       │
╞═══════════════╪═══════════════╪══════════════════╪═════════════════╪═════════════════╪═══════════╡
│ Aulagne       ┆ 1             ┆ 1240             ┆ [{{"François    ┆ {[{"Bernard AUL ┆ right     │
│               ┆               ┆                  ┆ MITTERRAND",523 ┆ AGNE",1232,1247 ┆           │
│               ┆               ┆                  ┆ ,5…             ┆ …               ┆           │
│ Aulagne       ┆ 1             ┆ 2866             ┆ [{{"François    ┆ {[{"Bernard AUL ┆ right     │
│               ┆               ┆                  ┆ MITTERRAND",523 ┆ AGNE",1232,1247 ┆           │
│               ┆               ┆                  ┆ ,5…             ┆ …               ┆           │
│ Pujol         ┆ 1             ┆ 208              ┆ [{{"JUQUIN",193 ┆ {[{"JUQUIN",147 ┆ left      │
│               ┆               ┆                  ┆ ,199},"left"},  ┆ 2,1478},        ┆           │
│               ┆               ┆                  ┆ …               ┆ {"PUJO…         ┆           │
│ Pujol         ┆ 1             ┆ 3567             ┆ [{{"JUQUIN",193 ┆ {[{"JUQUIN",147 ┆ left      │
│               ┆               ┆                  ┆ ,199},"left"},  ┆ 2,1478},        ┆           │
│               ┆               ┆                  ┆ …               ┆ {"PUJO…         ┆           │
│ Boyon         ┆ 1             ┆ 155              ┆ [{{"Jacques BOY ┆ {[{"Paul MORIN" ┆ left      │
│               ┆               ┆                  ┆ ON",147,160},"l ┆ ,4294,4304},    ┆           │
│               ┆               ┆                  ┆ …               ┆ {"…             ┆           │
│ …             ┆ …             ┆ …                ┆ …               ┆ …               ┆ …         │
│ Virapoullé    ┆ 2             ┆ 1360             ┆ [{{"JEAN-PAUL   ┆ {[{"Jean-Paul   ┆ right     │
│               ┆               ┆                  ┆ VIRAPOULLE",116 ┆ VIRAPOULLE",135 ┆           │
│               ┆               ┆                  ┆ ,…              ┆ 0…              ┆           │
│ Virapoullé    ┆ 2             ┆ 1425             ┆ [{{"JEAN-PAUL   ┆ {[{"Jean-Paul   ┆ right     │
│               ┆               ┆                  ┆ VIRAPOULLE",116 ┆ VIRAPOULLE",135 ┆           │
│               ┆               ┆                  ┆ ,…              ┆ 0…              ┆           │
│ Vergès        ┆ 2             ┆ 33               ┆ [{{"Paul VERGÈS ┆ {[{"Paul Vergès ┆ left      │
│               ┆               ┆                  ┆ ",28,39},"right ┆ ",1400,1411},   ┆           │
│               ┆               ┆                  ┆ …               ┆ {…              ┆           │
│ Vergès        ┆ 2             ┆ 1405             ┆ [{{"Paul VERGÈS ┆ {[{"Paul Vergès ┆ left      │
│               ┆               ┆                  ┆ ",28,39},"right ┆ ",1400,1411},   ┆           │
│               ┆               ┆                  ┆ …               ┆ {…              ┆           │
│ Vergès        ┆ 2             ┆ 3727             ┆ [{{"Paul VERGÈS ┆ {[{"Paul Vergès ┆ left      │
│               ┆               ┆                  ┆ ",28,39},"right ┆ ",1400,1411},   ┆           │
│               ┆               ┆                  ┆ …               ┆ {…              ┆           │
└───────────────┴───────────────┴──────────────────┴─────────────────┴─────────────────┴───────────┘

# Descriptive statistics

In [65]:
pl.read_parquet("df_gliner_full.parquet").shape

(3410, 47)

In [64]:
pl.read_parquet("df_gliner_full.parquet")

shape: (3_410, 47)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ date      ┆ subject   ┆ title     ┆ … ┆ transcrip ┆ titulaire ┆ titulaire ┆ res      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ t-normali ┆ -nom-norm ┆ -nom-posi ┆ ---      │
│ str       ┆ datetime[ ┆ str       ┆ str       ┆   ┆ zed       ┆ alized    ┆ tions     ┆ struct[3 │
│           ┆ μs]       ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ]        │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆ list[i64] ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ EL174_L_1 ┆ 1988-06-0 ┆ France;As ┆ Élections ┆ … ┆ elections ┆ aulagne   ┆ [1240,    ┆ {[{{"Fra │
│ 988_06_00 ┆ 5         ┆ semblée   ┆ législati ┆   ┆ legislati ┆           ┆ 2866]     ┆ nçois    │
│ 1_01_1_PF ┆ 00:00:00  ┆ Nationale ┆ ves de    ┆   ┆ ves du 5  ┆           ┆           ┆ MITTERRA │
│ _01       ┆           ┆ ;Ve …     ┆ 1988…     ┆   ┆ ju…       ┆           ┆           ┆ ND",523, │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ EL174_L_1 ┆ 1988-06-0 ┆ Élections ┆ Élections ┆ … ┆ republiqu ┆ pujol     ┆ [208,     ┆ {[{{"JUQ │
│ 988_06_00 ┆ 5         ┆ législati ┆ législati ┆   ┆ e         ┆           ┆ 3567]     ┆ UIN",193 │
│ 1_01_1_PF ┆ 00:00:00  ┆ ves;Assem ┆ ves de    ┆   ┆ francaise ┆           ┆           ┆ ,199},"l │
│ _02       ┆           ┆ bl…       ┆ 1988…     ┆   ┆ -         ┆           ┆           ┆ eft"},…  │
│           ┆           ┆           ┆           ┆   ┆ liberte…  ┆           ┆           ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Assemblée ┆ Élections ┆ … ┆ sciences  ┆ boyon     ┆ [155]     ┆ {[{{"Jac │
│ 988_06_00 ┆ 5         ┆ Nationale ┆ législati ┆   ┆ po /      ┆           ┆           ┆ ques BOY │
│ 1_01_1_PF ┆ 00:00:00  ┆ ;Ve       ┆ ves de    ┆   ┆ fonds     ┆           ┆           ┆ ON",147, │
│ _03       ┆           ┆ Républi…  ┆ 1988…     ┆   ┆ cevipof   ┆           ┆           ┆ 160},"…  │
│           ┆           ┆           ┆           ┆   ┆ el…       ┆           ┆           ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Assemblée ┆ Élections ┆ … ┆ sciences  ┆ saint-pie ┆ [102,     ┆ {[{{"PIE │
│ 988_06_00 ┆ 5         ┆ Nationale ┆ législati ┆   ┆ po /      ┆ rre       ┆ 1346]     ┆ RRE FROM │
│ 1_01_1_PF ┆ 00:00:00  ┆ ;Ve       ┆ ves de    ┆   ┆ fonds     ┆           ┆           ┆ ONT",115 │
│ _04       ┆           ┆ Républi…  ┆ 1988…     ┆   ┆ cevipof   ┆           ┆           ┆ ,129},…  │
│           ┆           ┆           ┆           ┆   ┆ re…       ┆           ┆           ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Ve Républ ┆ Élections ┆ … ┆ republiqu ┆ mornet    ┆ [84]      ┆ {[{{"Lio │
│ 988_06_00 ┆ 5         ┆ ique;Élec ┆ législati ┆   ┆ e         ┆           ┆           ┆ nel MORN │
│ 1_01_1_PF ┆ 00:00:00  ┆ tions     ┆ ves de    ┆   ┆ francaise ┆           ┆           ┆ ET",77,9 │
│ _05       ┆           ┆ législ…   ┆ 1988…     ┆   ┆ -         ┆           ┆           ┆ 0},"le…  │
│           ┆           ┆           ┆           ┆   ┆ liberte…  ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ EL177_L_1 ┆ 1988-06-1 ┆ Assemblée ┆ Élections ┆ … ┆ claude    ┆ hoarau    ┆ [7, 846,  ┆ {[{{"Cla │
│ 988_06_97 ┆ 2         ┆ Nationale ┆ législati ┆   ┆ hoarau    ┆           ┆ 3701]     ┆ ude HOAR │
│ 4_03_2_PF ┆ 00:00:00  ┆ ;Élection ┆ ves de    ┆   ┆ egalite   ┆           ┆           ┆ AU",0,13 │
│ _02       ┆           ┆ s …       ┆ 1988…     ┆   ┆ responsa… ┆           ┆           ┆ },"rig…  │
│ EL177_L_1 ┆ 1988-06-1 ┆ Ve Républ ┆ Élections ┆ … ┆ sciences  ┆ pihouee   ┆ [2005]    ┆ {[{{"Fre │
│ 988_06_97 ┆ 2         ┆ ique;Élec ┆ législati ┆   ┆ po /      ┆           ┆           ┆ d Lucien │
│ 4_04_2_PF ┆ 00:00:00  ┆ tions     ┆ ves de    ┆   ┆ fonds     ┆           ┆           ┆ ",62,73} │
│ _01       ┆           ┆ législ…   ┆ 1988…     ┆   ┆ cevipof   ┆           ┆           ┆ ,"righ…  │
│           ┆           ┆           ┆           ┆   ┆ an…       ┆           ┆           ┆          │
│ EL177_L_1 ┆ 1988-06-1 ┆ Ve Républ ┆ Élections ┆ … ┆ elie      ┆ hoarau    ┆ [5, 3694] ┆ {[{{"Éli │
│ 988_06_97 ┆ 2         ┆ ique;Élec ┆ législati ┆   ┆ hoarau    ┆           ┆           ┆ e HOARAU │
│ 4_04_2_PF ┆ 00:00:00  ┆ tions     ┆ ves de    ┆   ┆ egalite   ┆           ┆           ┆ ",0,11}, │
│ _02       ┆           ┆ législ…   ┆ 1988…     ┆   ┆ responsab ┆           ┆           ┆ "right…  │
│           ┆           ┆           ┆           ┆   ┆ i…        ┆           ┆           ┆          │
│ EL177_L_1 ┆ 1988-06-1 ┆ France;Ve ┆ Élections ┆ … ┆ sciences  ┆ virapoull ┆ [126,     ┆ {[{{"JEA │
│ 988_06_97 ┆ 2         ┆ Républiqu ┆ législati ┆   ┆ po /      ┆ e         ┆ 1360,     ┆ N-PAUL   │
│ 4_05_2_PF ┆ 00:00:00  ┆ e;Assembl ┆ ves de    ┆   ┆ fonds     ┆           ┆ 1425]     ┆ VIRAPOUL │
│ _01       ┆           ┆ ée…       ┆ 1988…     ┆   ┆ cevipof   ┆           ┆           ┆ LE",116… │
│           ┆           ┆           ┆           ┆   ┆ el…       ┆           ┆           ┆          │
│ EL177_L_1 ┆ 1988-06-1 ┆ Assemblée ┆ Élections ┆ … ┆ sciences  ┆ verges    ┆ [33,      ┆ {[{{"Pau │
│ 988_06_97 ┆ 2         ┆ Nationale ┆ législati ┆   ┆ po /      ┆           ┆ 1405,     ┆ l VERGÈS │
│ 4_05_2_PF ┆ 00:00:00  ┆ ;Élection ┆ ves de    ┆   ┆ fonds     ┆           ┆ 3727]     ┆ ",28,39} │
│ _02       ┆           ┆ s …       ┆ 1988…     ┆   ┆ cevipof   ┆           ┆           ┆ ,"righ…  │
│           ┆           ┆           ┆           ┆   ┆ pa…       ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [28]:
def position_is_inside_span(pos:int, span):
    # Returns a boolean
    # True if position is inside the span
    return (pos >= span["start"]) & (pos < span["end"])

df = df.unnest("entities").with_columns(
    pl.struct(["titulaire-nom-positions","PER"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["PER"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-PER"),
    pl.struct(["titulaire-nom-positions","PER_LEFT"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["PER_LEFT"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-PER_LEFT"),
    pl.struct(["titulaire-nom-positions","PER_RIGHT"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["PER_RIGHT"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-PER_RIGHT"),
    pl.struct(["titulaire-nom-positions","PER_GAUCHE"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["PER_GAUCHE"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-PER_GAUCHE"),
    pl.struct(["titulaire-nom-positions","PER_DROITE"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["PER_DROITE"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-PER_DROITE"),
    pl.struct(["titulaire-nom-positions","ORG"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["ORG"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-ORG"),
    pl.struct(["titulaire-nom-positions","LOC"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["LOC"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-LOC")
)

In [61]:
df.select(pl.selectors.by_name("titulaire-nom","titulaire-nom-positions","is-in-PER","PER","is-in-PER_LEFT"))

shape: (9_010, 5)
┌───────────────┬─────────────────────────┬───────────┬───────────────────────────┬────────────────┐
│ titulaire-nom ┆ titulaire-nom-positions ┆ is-in-PER ┆ PER                       ┆ is-in-PER_LEFT │
│ ---           ┆ ---                     ┆ ---       ┆ ---                       ┆ ---            │
│ str           ┆ i64                     ┆ bool      ┆ list[struct[3]]           ┆ bool           │
╞═══════════════╪═════════════════════════╪═══════════╪═══════════════════════════╪════════════════╡
│ Aulagne       ┆ 1240                    ┆ true      ┆ [{"Bernard                ┆ false          │
│               ┆                         ┆           ┆ AULAGNE",1232,1247}…      ┆                │
│ Aulagne       ┆ 2866                    ┆ false     ┆ [{"Bernard                ┆ false          │
│               ┆                         ┆           ┆ AULAGNE",1232,1247}…      ┆                │
│ Pujol         ┆ 208                     ┆ true      ┆ [{"JUQUIN",1472,1478},    ┆ false          │
│               ┆                         ┆           ┆ {"PUJOL…                  ┆                │
│ Pujol         ┆ 3567                    ┆ false     ┆ [{"JUQUIN",1472,1478},    ┆ false          │
│               ┆                         ┆           ┆ {"PUJOL…                  ┆                │
│ Boyon         ┆ 155                     ┆ true      ┆ [{"Paul                   ┆ false          │
│               ┆                         ┆           ┆ MORIN",4294,4304}, {"J…   ┆                │
│ …             ┆ …                       ┆ …         ┆ …                         ┆ …              │
│ Virapoullé    ┆ 1360                    ┆ true      ┆ [{"Jean-Paul              ┆ false          │
│               ┆                         ┆           ┆ VIRAPOULLE",1350,…        ┆                │
│ Virapoullé    ┆ 1425                    ┆ false     ┆ [{"Jean-Paul              ┆ false          │
│               ┆                         ┆           ┆ VIRAPOULLE",1350,…        ┆                │
│ Vergès        ┆ 33                      ┆ false     ┆ [{"Paul                   ┆ false          │
│               ┆                         ┆           ┆ Vergès",1400,1411}, {"…   ┆                │
│ Vergès        ┆ 1405                    ┆ true      ┆ [{"Paul                   ┆ false          │
│               ┆                         ┆           ┆ Vergès",1400,1411}, {"…   ┆                │
│ Vergès        ┆ 3727                    ┆ false     ┆ [{"Paul                   ┆ false          │
│               ┆                         ┆           ┆ Vergès",1400,1411}, {"…   ┆                │
└───────────────┴─────────────────────────┴───────────┴───────────────────────────┴────────────────┘

# Results and discussion

## PER, LOC, ORG tasks

In [62]:
df.with_columns(weight=1).select(pl.sum("is-in-PER","weight")
).with_columns(
    recall = pl.col("is-in-PER")/pl.col("weight")
).select(pl.selectors.by_name("is-in-PER","weight","recall"))

shape: (1, 3)
┌───────────┬────────┬──────────┐
│ is-in-PER ┆ weight ┆ recall   │
│ ---       ┆ ---    ┆ ---      │
│ u32       ┆ i32    ┆ f64      │
╞═══════════╪════════╪══════════╡
│ 3283      ┆ 9010   ┆ 0.364373 │
└───────────┴────────┴──────────┘

In [42]:
toto = df.get_column("is-in-PER").value_counts().rows_by_key("is-in-PER", unique=True)

shape: (1, 3)
┌───────────┬────────┬──────────┐
│ is-in-PER ┆ weight ┆ recall   │
│ ---       ┆ ---    ┆ ---      │
│ u32       ┆ i32    ┆ f64      │
╞═══════════╪════════╪══════════╡
│ 3283      ┆ 9010   ┆ 0.364373 │
└───────────┴────────┴──────────┘

In [53]:
df.with_columns(weight=1).group_by(
    pl.col("titulaire-nom"),maintain_order=True
).agg(
    pl.col("is-in-PER").sum().alias("toto"),
    pl.col("weight").sum().alias("total")
).with_columns(
    recall = pl.col("toto")/pl.col("total")
).select(pl.selectors.by_name("titulaire-nom","toto","total","recall"))

shape: (2_308, 4)
┌───────────────┬──────┬───────┬────────┐
│ titulaire-nom ┆ toto ┆ total ┆ recall │
│ ---           ┆ ---  ┆ ---   ┆ ---    │
│ str           ┆ u32  ┆ i32   ┆ f64    │
╞═══════════════╪══════╪═══════╪════════╡
│ Aulagne       ┆ 1    ┆ 2     ┆ 0.5    │
│ Pujol         ┆ 1    ┆ 2     ┆ 0.5    │
│ Boyon         ┆ 2    ┆ 2     ┆ 1.0    │
│ Saint-Pierre  ┆ 2    ┆ 4     ┆ 0.5    │
│ Mornet        ┆ 1    ┆ 1     ┆ 1.0    │
│ …             ┆ …    ┆ …     ┆ …      │
│ Poillot       ┆ 1    ┆ 1     ┆ 1.0    │
│ Delaporte     ┆ 1    ┆ 1     ┆ 1.0    │
│ Jégou         ┆ 0    ┆ 2     ┆ 0.0    │
│ Larifla       ┆ 0    ┆ 1     ┆ 0.0    │
│ Clery         ┆ 1    ┆ 1     ┆ 1.0    │
└───────────────┴──────┴───────┴────────┘

In [8]:
df[0]["entities"]["PER"]

TypeError: cannot select elements using Sequence with elements of type 'str'