# Data analysis

In [1]:
import contextlib
import pandas as pd
import polars as pl
from tqdm import tqdm

# Loading the data

In [4]:
df = pl.read_parquet("df_gliner_full.parquet").unnest("res").explode("titulaire-nom-positions")
df.select(pl.selectors.by_name("titulaire-nom","titulaire-nom-positions","person","entities","political ideology"))

shape: (9_010, 5)
┌───────────────┬───────────────────────┬───────────────────────┬──────────────────────┬───────────┐
│ titulaire-nom ┆ titulaire-nom-positio ┆ person                ┆ entities             ┆ political │
│ ---           ┆ ns                    ┆ ---                   ┆ ---                  ┆ ideology  │
│ str           ┆ ---                   ┆ list[struct[2]]       ┆ struct[7]            ┆ ---       │
│               ┆ i64                   ┆                       ┆                      ┆ str       │
╞═══════════════╪═══════════════════════╪═══════════════════════╪══════════════════════╪═══════════╡
│ Aulagne       ┆ 1240                  ┆ [{{"François          ┆ {[{"Bernard          ┆ right     │
│               ┆                       ┆ MITTERRAND",523,5…    ┆ AULAGNE",1232,1247…  ┆           │
│ Aulagne       ┆ 2866                  ┆ [{{"François          ┆ {[{"Bernard          ┆ right     │
│               ┆                       ┆ MITTERRAND",523,5…    ┆ AULAGNE",1232,1247…  ┆           │
│ Pujol         ┆ 208                   ┆ [{{"JUQUIN",193,199}, ┆ {[{"JUQUIN",1472,147 ┆ left      │
│               ┆                       ┆ "left"}, …            ┆ 8}, {"PUJO…          ┆           │
│ Pujol         ┆ 3567                  ┆ [{{"JUQUIN",193,199}, ┆ {[{"JUQUIN",1472,147 ┆ left      │
│               ┆                       ┆ "left"}, …            ┆ 8}, {"PUJO…          ┆           │
│ Boyon         ┆ 155                   ┆ [{{"Jacques           ┆ {[{"Paul             ┆ left      │
│               ┆                       ┆ BOYON",147,160},"l…   ┆ MORIN",4294,4304},   ┆           │
│               ┆                       ┆                       ┆ {"…                  ┆           │
│ …             ┆ …                     ┆ …                     ┆ …                    ┆ …         │
│ Virapoullé    ┆ 1360                  ┆ [{{"JEAN-PAUL         ┆ {[{"Jean-Paul        ┆ right     │
│               ┆                       ┆ VIRAPOULLE",116,…     ┆ VIRAPOULLE",1350…    ┆           │
│ Virapoullé    ┆ 1425                  ┆ [{{"JEAN-PAUL         ┆ {[{"Jean-Paul        ┆ right     │
│               ┆                       ┆ VIRAPOULLE",116,…     ┆ VIRAPOULLE",1350…    ┆           │
│ Vergès        ┆ 33                    ┆ [{{"Paul VERGÈS",28,3 ┆ {[{"Paul             ┆ left      │
│               ┆                       ┆ 9},"right…            ┆ Vergès",1400,1411},  ┆           │
│               ┆                       ┆                       ┆ {…                   ┆           │
│ Vergès        ┆ 1405                  ┆ [{{"Paul VERGÈS",28,3 ┆ {[{"Paul             ┆ left      │
│               ┆                       ┆ 9},"right…            ┆ Vergès",1400,1411},  ┆           │
│               ┆                       ┆                       ┆ {…                   ┆           │
│ Vergès        ┆ 3727                  ┆ [{{"Paul VERGÈS",28,3 ┆ {[{"Paul             ┆ left      │
│               ┆                       ┆ 9},"right…            ┆ Vergès",1400,1411},  ┆           │
│               ┆                       ┆                       ┆ {…                   ┆           │
└───────────────┴───────────────────────┴───────────────────────┴──────────────────────┴───────────┘

In [28]:
def position_is_inside_span(pos:int, span):
    # Returns a boolean
    # True if position is inside the span
    return (pos >= span["start"]) & (pos < span["end"])

df = df.unnest("entities").with_columns(
    pl.struct(["titulaire-nom-positions","PER"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["PER"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-PER"),
    pl.struct(["titulaire-nom-positions","PER_LEFT"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["PER_LEFT"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-PER_LEFT"),
    pl.struct(["titulaire-nom-positions","PER_RIGHT"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["PER_RIGHT"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-PER_RIGHT"),
    pl.struct(["titulaire-nom-positions","PER_GAUCHE"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["PER_GAUCHE"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-PER_GAUCHE"),
    pl.struct(["titulaire-nom-positions","PER_DROITE"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["PER_DROITE"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-PER_DROITE"),
    pl.struct(["titulaire-nom-positions","ORG"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["ORG"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-ORG"),
    pl.struct(["titulaire-nom-positions","LOC"])
    .map_elements(lambda s: any([position_is_inside_span(s["titulaire-nom-positions"],span) for span in s["LOC"]]), 
                  return_dtype=pl.Boolean)
    .alias("is-in-LOC")
)
# df.select(pl.selectors.by_name("titulaire-nom","titulaire-nom-positions","is-in-PER","PER","is-in-PER_LEFT"))

In [42]:
toto = df.get_column("is-in-PER").value_counts().rows_by_key("is-in-PER", unique=True)

In [58]:
df.with_columns(weight=1).select(pl.sum("is-in-PER","weight")
).with_columns(
    recall = pl.col("is-in-PER")/pl.col("weight")
).select(pl.selectors.by_name("is-in-PER","weight","recall"))

shape: (1, 3)
┌───────────┬────────┬──────────┐
│ is-in-PER ┆ weight ┆ recall   │
│ ---       ┆ ---    ┆ ---      │
│ u32       ┆ i32    ┆ f64      │
╞═══════════╪════════╪══════════╡
│ 3283      ┆ 9010   ┆ 0.364373 │
└───────────┴────────┴──────────┘

In [53]:
df.with_columns(weight=1).group_by(
    pl.col("titulaire-nom"),maintain_order=True
).agg(
    pl.col("is-in-PER").sum().alias("toto"),
    pl.col("weight").sum().alias("total")
).with_columns(
    recall = pl.col("toto")/pl.col("total")
).select(pl.selectors.by_name("titulaire-nom","toto","total","recall"))

shape: (2_308, 4)
┌───────────────┬──────┬───────┬────────┐
│ titulaire-nom ┆ toto ┆ total ┆ recall │
│ ---           ┆ ---  ┆ ---   ┆ ---    │
│ str           ┆ u32  ┆ i32   ┆ f64    │
╞═══════════════╪══════╪═══════╪════════╡
│ Aulagne       ┆ 1    ┆ 2     ┆ 0.5    │
│ Pujol         ┆ 1    ┆ 2     ┆ 0.5    │
│ Boyon         ┆ 2    ┆ 2     ┆ 1.0    │
│ Saint-Pierre  ┆ 2    ┆ 4     ┆ 0.5    │
│ Mornet        ┆ 1    ┆ 1     ┆ 1.0    │
│ …             ┆ …    ┆ …     ┆ …      │
│ Poillot       ┆ 1    ┆ 1     ┆ 1.0    │
│ Delaporte     ┆ 1    ┆ 1     ┆ 1.0    │
│ Jégou         ┆ 0    ┆ 2     ┆ 0.0    │
│ Larifla       ┆ 0    ┆ 1     ┆ 0.0    │
│ Clery         ┆ 1    ┆ 1     ┆ 1.0    │
└───────────────┴──────┴───────┴────────┘

In [8]:
df[0]["entities"]["PER"]

TypeError: cannot select elements using Sequence with elements of type 'str'