# Exploration CSV
Objectif = exploration du contenu du fichier CSV

## Résumé
Le csv contient:
- une ligne par profession de foi (mais les transcriptions ne sont pas toutes disponibles)
- depuis 1958,
- plusieurs types d'élection : présidentielles, législatives, européennes, la plupart des documents proviennent des élections législatives
- le premier et le deuxième tour

In [77]:
import pandas as pd
import contextlib
import pickle

In [3]:
csv = pd.read_csv("archelect_search.csv")

/tmp/ipykernel_1109/3805055519.py:1: DtypeWarning: Columns (0: departement-nom, 1: departement-insee, 2: identifiant de circonscription, 3: pdf, 4: suppleant-nom, 5: suppleant-prenom, 6: suppleant-sexe, 7: suppleant-age, 8: suppleant-age-calcule, 9: suppleant-age-tranche, 10: suppleant-profession, 11: suppleant-mandat-en-cours, 12: suppleant-mandat-passe, 13: suppleant-associations, 14: suppleant-autres-statuts, 15: suppleant-soutien, 16: suppleant-liste, 17: suppleant-decorations) have mixed types. Specify dtype option on import or set low_memory=False.
  csv = pd.read_csv("archelect_search.csv")

In [4]:
csv.shape

(33030, 42)

In [5]:
csv.columns

Index(['id', 'date', 'subject', 'title', 'contexte-election', 'contexte-tour',
       'cote', 'departement', 'departement-nom', 'departement-insee',
       'identifiant de circonscription', 'images', 'pdf', 'ocr_url',
       'titulaire-nom', 'titulaire-prenom', 'titulaire-sexe', 'titulaire-age',
       'titulaire-age-calcule', 'titulaire-age-tranche',
       'titulaire-profession', 'titulaire-mandat-en-cours',
       'titulaire-mandat-passe', 'titulaire-associations',
       'titulaire-autres-statuts', 'titulaire-soutien', 'titulaire-liste',
       'titulaire-decorations', 'suppleant-nom', 'suppleant-prenom',
       'suppleant-sexe', 'suppleant-age', 'suppleant-age-calcule',
       'suppleant-age-tranche', 'suppleant-profession',
       'suppleant-mandat-en-cours', 'suppleant-mandat-passe',
       'suppleant-associations', 'suppleant-autres-statuts',
       'suppleant-soutien', 'suppleant-liste', 'suppleant-decorations'],
      dtype='str')

In [6]:
csv.head()

,id,date,subject,title,contexte-election,contexte-tour,cote,departement,departement-nom,departement-insee,...,suppleant-age-calcule,suppleant-age-tranche,suppleant-profession,suppleant-mandat-en-cours,suppleant-mandat-passe,suppleant-associations,suppleant-autres-statuts,suppleant-soutien,suppleant-liste,suppleant-decorations
0,EL009_L_1958_11_001_01_1_PF_01,1958-11-23,France;Élections législatives;Assemblée Nation...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur,maire;conseiller général,non mentionné,non mentionné,non mentionné,Parti radical,non mentionné,non
1,EL009_L_1958_11_001_01_1_PF_02,1958-11-23,France;Ve République;Élections législatives;As...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur,conseiller municipal,non mentionné,non mentionné,prisonnier de guerre,Union pour la nouvelle République,non mentionné,non
2,EL009_L_1958_11_001_01_1_PF_03,1958-11-23,Élections législatives;France;Assemblée Nation...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur,non mentionné,non mentionné,non mentionné,non mentionné,Parti communiste français,non mentionné,non
3,EL009_L_1958_11_001_01_1_PF_04,1958-11-23,Élections législatives;France;Assemblée Nation...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,35,entre 30 et 39 ans,greffier de paix,conseiller municipal;conseiller général,non mentionné,non mentionné,combattant,non mentionné,non mentionné,oui
4,EL009_L_1958_11_001_01_1_PF_05,1958-11-23,Ve République;Assemblée Nationale;Élections lé...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur;président Coopérative élevage,non mentionné,non mentionné,non mentionné,non mentionné,Centre national des indépendants et paysans,non mentionné,non

# Sélection de colonnes

In [7]:
# select id column as string => index / sql key
csv["id"][25000]

'EL176_L_1988_06_069_10_1_PF_04'

In [8]:
# select date and convert as date
csv['date'] = pd.to_datetime(csv['date'])
csv['date'].head()

0   1958-11-23
1   1958-11-23
2   1958-11-23
3   1958-11-23
4   1958-11-23
Name: date, dtype: datetime64[us]

In [9]:
# example: keep only 1988 election
csv['contexte-tour'].loc[csv['date'].dt.year==1988]

23341    1
23342    1
23343    1
23344    1
23345    1
        ..
26887    2
26888    2
26889    2
26890    2
26891    2
Name: contexte-tour, Length: 3551, dtype: int64

In [10]:
csv['contexte-election'].value_counts()

contexte-election
législatives               32625
européennes                  235
présidentielle               106
régionales                    25
législatives|régionales       17
législatives partielles       14
cantonales                     8
Name: count, dtype: int64

In [11]:
with open("text_files/1988/legislatives/"+csv["id"][25000]+".txt", "r") as file:
    content = file.read()
print(content)

Sciences Po / fonds CEVIPOF
ÉLECTIONS LÉGISLATIVES DU 5 JUIN 1988 - 10e circonscription du RHÔNE
MAJORITÉ PRÉSIDENTIELLE POUR LA FRANCE UNIE
V
Yvette PERRIN-RISS
Titulaire
Christiane CONSTANT SuppléanteSciences Po / fonds CEVIPOF
Madame, Mademoiselle, Monsieur,
Pourquoi avoir accepté d'être candidate aux législatives à la demande des militants du PS aux côtés de Christiane CONSTANT ?
Veuve à 32 ans avec quatre enfants, j'ai dû réagir. Je me suis battue pour faire aboutir les droits légitimes de toutes les familles. Il était donc normal que je réponde positivement, dans une période où le risque d'avoir une société à deux vitesses se précise tous les jours.
- Nous aurons à nous opposer « à des drames qui s'appellent : le chômage, l'exclusion, les dangers pour la paix ou les entraves au développement du tiers monde », message de Michel ROCARD le 14 mai 1988.
- Nous aurons à construire ensemble autour des principes de la démocratie et de la solidarité.
- J'ai été particulièrement heureuse que la première mesure prise par le gou- vernement « d'ouverture » soit l'institution d'un revenu minimum pour tous.
- Mais les mesures de solidarité ne suffisent pas, encore faut-il avoir une économie forte qui produise des richesses, n'oublions pas que c'est la gau- che qui a réconcilié les Français avec leur industrie.
- Mais une agriculture vivante est également indispensable aussi bien à l'équi- libre économique qu'au maintien d'un environnement de qualité. Il faudra y être attentif, quelles que soient les contraintes.
- La formation doit être aussi un impératif national, tant sur le plan de l'effi- cacité que de la solidarité. Il faut donner à nos jeunes toutes leurs chances. Il faut donner de nouvelles possibilités à ceux qui n'ont pu acquérir jeune le bagage suffisant.
L'action concrète et pratique que j'ai menée depuis plus de 20 ans sur le plan départemental, puis national, m'a donné l'habitude de prendre en charge des dossiers complexes.
Ce sera difficile, mais je crois pouvoir avec vous, et si vous me faites confiance, permettre à chaque femme et à chaque homme d'être porteur d'espérance.
Christiane CONSTANT, depuis de nombreuses années dans l'action sociale, sera à mes côtés pour rendre plus efficaces ces volontés.
Yvette PERRIN-RISS
Vu, le Candidat
AG - TORCY

# Filtrer les documents disponibles et vérifier que la transcription existe

on a des infos sur le titulaire : profession, age
la question est comment faire des liaisons pour avoir un réseau : 
appartenance à un parti : sera très fragmenté / clusters
proximité des documents : nécessite de définir un threshold (faire de sorte à matcher un réseau de personnes, puis explorer le réseau pour voir si cela correspond aux caractéristiques d'un réseau de personnes, par exemple la transitivité)

In [88]:
# select 1988 election (because we only have transcriptions for this election)
csv1988 = csv.loc[(csv['date'].dt.year==1988) & (csv['contexte-election']=='législatives')]

In [89]:
# check that this corresponds to the legislatives
print(csv1988['contexte-election'].value_counts())
print(csv1988["contexte-tour"].value_counts())

contexte-election
législatives    3540
Name: count, dtype: int64
contexte-tour
1    2686
2     854
Name: count, dtype: int64

In [93]:
csv1988["id"]

23352    EL174_L_1988_06_001_01_1_PF_01
23353    EL174_L_1988_06_001_01_1_PF_02
23354    EL174_L_1988_06_001_01_1_PF_03
23355    EL174_L_1988_06_001_01_1_PF_04
23356    EL174_L_1988_06_001_01_1_PF_05
                      ...
26887    EL177_L_1988_06_974_03_2_PF_02
26888    EL177_L_1988_06_974_04_2_PF_01
26889    EL177_L_1988_06_974_04_2_PF_02
26890    EL177_L_1988_06_974_05_2_PF_01
26891    EL177_L_1988_06_974_05_2_PF_02
Name: id, Length: 3540, dtype: str

In [94]:
for row in csv1988.itertuples():
    with contextlib.suppress(FileNotFoundError):
        with open("text_files/1988/legislatives/"+row.id+".txt", "r") as file:
            content = file.read()
        csv1988.loc[row.Index,"transcript"] = content
        csv1988.loc[row.Index,"transcript_length"] = len(content)

In [95]:
csv1988["transcript_length"].value_counts()

transcript_length
5282.0    26
5283.0    16
5281.0    11
5284.0    11
2925.0     7
          ..
1586.0     1
1300.0     1
3200.0     1
2040.0     1
3978.0     1
Name: count, Length: 2382, dtype: int64

In [96]:
with open("csv1988.pkl", "wb") as f:
    pickle.dump(csv1988, f)

In [97]:
csv1988["transcript_length"].describe()

count     3539.000000
mean      3503.620514
std       1596.286080
min        377.000000
25%       2481.000000
50%       3092.000000
75%       4280.000000
max      15489.000000
Name: transcript_length, dtype: float64

In [32]:
csv1988.loc[0,"transcript"] = "tata"

In [33]:
csv1988["transcript"].value_counts()

transcript
        3541
tata       1
Name: count, dtype: int64

In [61]:
csv1988

,id,date,subject,title,contexte-election,contexte-tour,cote,departement,departement-nom,departement-insee,...,suppleant-age-tranche,suppleant-profession,suppleant-mandat-en-cours,suppleant-mandat-passe,suppleant-associations,suppleant-autres-statuts,suppleant-soutien,suppleant-liste,suppleant-decorations,"(EL174_L_1988_06_001_01_1_PF_03, transcript)"
23352,EL174_L_1988_06_001_01_1_PF_01,1988-06-05,France;Assemblée Nationale;Ve République;Élect...,"Élections législatives de 1988, Ain - 01, circ...",législatives,1,EL174,01,Ain,01 - Ain,...,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,Front national,Liste d'entente populaire et nationale,non,Sciences Po / fonds CEVIPOF\nELECTIONS LEGISLA...
23353,EL174_L_1988_06_001_01_1_PF_02,1988-06-05,Élections législatives;Assemblée Nationale;Ve ...,"Élections législatives de 1988, Ain - 01, circ...",législatives,1,EL174,01,Ain,01 - Ain,...,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,Comités Juquin,Une nouvelle politique à gauche,non,Sciences Po / fonds CEVIPOF\nELECTIONS LEGISLA...
23354,EL174_L_1988_06_001_01_1_PF_03,1988-06-05,Assemblée Nationale;Ve République;Élections lé...,"Élections législatives de 1988, Ain - 01, circ...",législatives,1,EL174,01,Ain,01 - Ain,...,non mentionné,non mentionné,conseiller général,maire-adjoint honoraire,non mentionné,non mentionné,Rassemblement pour la République;Union pour la...,Union du rassemblement et du centre,oui,Sciences Po / fonds CEVIPOF\nELECTIONS LEGISLA...
23355,EL174_L_1988_06_001_01_1_PF_04,1988-06-05,Assemblée Nationale;Ve République;France;Élect...,"Élections législatives de 1988, Ain - 01, circ...",législatives,1,EL174,01,Ain,01 - Ain,...,entre 50 et 59 ans,agriculteur,conseiller général;maire,non mentionné,non mentionné,non mentionné,non mentionné,Bresse unie majorité présidentielle,non,Sciences Po / fonds CEVIPOF\nELECTIONS LEGISLA...
23356,EL174_L_1988_06_001_01_1_PF_05,1988-06-05,Ve République;Élections législatives;Assemblée...,"Élections législatives de 1988, Ain - 01, circ...",législatives,1,EL174,01,Ain,01 - Ain,...,entre 40 et 49 ans,employée,non mentionné,non mentionné,non mentionné,non mentionné,Parti communiste français,Rassemblement des forces de gauche,non,Sciences Po / fonds CEVIPOF\nELECTIONS LEGISLA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26887,EL177_L_1988_06_974_03_2_PF_02,1988-06-12,Assemblée Nationale;Élections législatives;Ve ...,"Élections législatives de 1988, Réunion - 974,...",législatives,2,EL177,974,Réunion,974 - La Réunion,...,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,Parti communiste réunionnais,Majorité présidentielle,non,Sciences Po / fonds CEVIPOF\nELECTIONS LEGISLA...
26888,EL177_L_1988_06_974_04_2_PF_01,1988-06-12,Ve République;Élections législatives;Assemblée...,"Élections législatives de 1988, Réunion - 974,...",législatives,2,EL177,974,Réunion,974 - La Réunion,...,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non,Sciences Po / fonds CEVIPOF\nELECTIONS LEGISLA...
26889,EL177_L_1988_06_974_04_2_PF_02,1988-06-12,Ve République;Élections législatives;France;As...,"Élections législatives de 1988, Réunion - 974,...",législatives,2,EL177,974,Réunion,974 - La Réunion,...,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,Parti communiste réunionnais,Majorité présidentielle,non,Sciences Po / fonds CEVIPOF\nELECTIONS LEGISLA...
26890,EL177_L_1988_06_974_05_2_PF_01,1988-06-12,France;Ve République;Assemblée Nationale;Élect...,"Élections législatives de 1988, Réunion - 974,...",législatives,2,EL177,974,Réunion,974 - La Réunion,...,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,Union du rassemblement et du centre,non,Sciences Po / fonds CEVIPOF\nELECTIONS LEGISLA...
26891,EL177_L_1988_06_974_05_2_PF_02,1988-06-12,Assemblée Nationale;Élections législatives;Ve ...,"Élections législatives de 1988, Réunion - 974,...",législatives,2,EL177,974,Réunion,974 - La Réunion,...,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,non mentionné,Parti communiste réunionnais,Majorité présidentielle,non,Sciences Po / fonds CEVIPOF\nELECTIONS LEGISLA...