# Projet NLP : Named entity recognition du titulaire / suppléant et de son affiliation politique

# Objectifs

On souhaite évaluer la performance d'une méthode Named-Entity-Recognition pour l'identification du titulaire de la profession de foi et de son affiliation politique. Pour cela, on tire parti des annotations disponibles, pour tagger les noms des titulaires / suppléants dans les transcriptions.

Plus précisément, on évalue ici la performance de GlinNER2 car : 
- c'est un modèle de type transformer de petite taille, uniquement CPU
- le modèle permet de faire du zero-shot learning et permet d'indiquer que l'on souhaite avoir l'affiliation politique correspondante à l'entité reconnue

# Annotations / création d'un jeu de test

On annote les professions de foi à partir des métadonnées disponibles.
Résulat : 
- liste des segments de texte où apparaissent le nom du titulaire / suppléant 
- affiliation politique de la profession de foi

## Lecture des métadonnées

In [11]:
import contextlib
import pandas as pd
import polars as pl

In [7]:
csv = pd.read_csv("archelect_search.csv")
csv['date'] = pd.to_datetime(csv['date'])

/tmp/ipykernel_2178/2974932302.py:1: DtypeWarning: Columns (0: departement-nom, 1: departement-insee, 2: identifiant de circonscription, 3: pdf, 4: suppleant-nom, 5: suppleant-prenom, 6: suppleant-sexe, 7: suppleant-age, 8: suppleant-age-calcule, 9: suppleant-age-tranche, 10: suppleant-profession, 11: suppleant-mandat-en-cours, 12: suppleant-mandat-passe, 13: suppleant-associations, 14: suppleant-autres-statuts, 15: suppleant-soutien, 16: suppleant-liste, 17: suppleant-decorations) have mixed types. Specify dtype option on import or set low_memory=False.
  csv = pd.read_csv("archelect_search.csv")

In [8]:
# select 1988 election (because we only have transcriptions for this election)
csv1988 = csv.loc[(csv['date'].dt.year==1988) & (csv['contexte-election']=='législatives')]

In [9]:
for row in csv1988.itertuples():
    with contextlib.suppress(FileNotFoundError):
        with open("text_files/1988/legislatives/"+row.id+".txt", "r") as file:
            content = file.read()
        csv1988.loc[row.Index,"transcript"] = content
        csv1988.loc[row.Index,"transcript_length"] = len(content)

## Normalisation du nom

In [10]:
# On utilise la librairie unidecode pour normaliser le nom du titulaire

from unidecode import unidecode
s = "stävänger"

# Convert characters to their closest ASCII equivalents
res = unidecode(s)
print(res)

stavanger

In [28]:
df = pl.from_pandas(csv1988)

In [35]:
df = df.with_columns(
    transcript_normalized = pl.col("transcript").str.to_lowercase()
      .str.normalize("NFKD")
      .str.replace_all(r"\p{CombiningMark}", ""),
    titulaire_nom_normalized = pl.col("titulaire-nom").str.to_lowercase()
      .str.normalize("NFKD")
      .str.replace_all(r"\p{CombiningMark}", ""),
    titulaire_nom_is_in_transcript = pl.col("transcript_normalized")
        .str.contains(pl.col("titulaire_nom_normalized"))

)

In [36]:
df.select(pl.selectors.by_name("titulaire-nom","titulaire_nom_normalized","titulaire_nom_is_in_transcript"))

shape: (3_540, 3)
┌───────────────┬──────────────────────────┬────────────────────────────────┐
│ titulaire-nom ┆ titulaire_nom_normalized ┆ titulaire_nom_is_in_transcript │
│ ---           ┆ ---                      ┆ ---                            │
│ str           ┆ str                      ┆ bool                           │
╞═══════════════╪══════════════════════════╪════════════════════════════════╡
│ Aulagne       ┆ aulagne                  ┆ true                           │
│ Pujol         ┆ pujol                    ┆ true                           │
│ Boyon         ┆ boyon                    ┆ true                           │
│ Saint-Pierre  ┆ saint-pierre             ┆ true                           │
│ Mornet        ┆ mornet                   ┆ true                           │
│ …             ┆ …                        ┆ …                              │
│ Hoarau        ┆ hoarau                   ┆ true                           │
│ Pihouee       ┆ pihouee                  ┆ true                           │
│ Hoarau        ┆ hoarau                   ┆ true                           │
│ Virapoullé    ┆ virapoulle               ┆ true                           │
│ Vergès        ┆ verges                   ┆ true                           │
└───────────────┴──────────────────────────┴────────────────────────────────┘

In [37]:
df.get_column("titulaire_nom_is_in_transcript").value_counts()

shape: (3, 2)
┌────────────────────────────────┬───────┐
│ titulaire_nom_is_in_transcript ┆ count │
│ ---                            ┆ ---   │
│ bool                           ┆ u32   │
╞════════════════════════════════╪═══════╡
│ false                          ┆ 129   │
│ null                           ┆ 1     │
│ true                           ┆ 3410  │
└────────────────────────────────┴───────┘

## Position du nom dans le transcript

In [39]:
df = df.with_columns(
    position_nom = pl.col("transcript_normalized").str.find(pl.col("titulaire_nom_normalized"))
)

In [42]:
df.select(pl.selectors.by_name("transcript","titulaire-nom","position_nom","titulaire_nom_is_in_transcript"))

shape: (3_540, 4)
┌─────────────────────────────────┬───────────────┬──────────────┬────────────────────────────────┐
│ transcript                      ┆ titulaire-nom ┆ position_nom ┆ titulaire_nom_is_in_transcript │
│ ---                             ┆ ---           ┆ ---          ┆ ---                            │
│ str                             ┆ str           ┆ u32          ┆ bool                           │
╞═════════════════════════════════╪═══════════════╪══════════════╪════════════════════════════════╡
│ Élections Législatives du 5 Ju… ┆ Aulagne       ┆ 1240         ┆ true                           │
│ RÉPUBLIQUE FRANÇAISE - Liberté… ┆ Pujol         ┆ 208          ┆ true                           │
│ Sciences Po / fonds CEVIPOF     ┆ Boyon         ┆ 155          ┆ true                           │
│ EL…                             ┆               ┆              ┆                                │
│ Sciences Po / fonds CEVIPOF     ┆ Saint-Pierre  ┆ 102          ┆ true                           │
│ RÉ…                             ┆               ┆              ┆                                │
│ RÉPUBLIQUE FRANÇAISE - LIBERTÉ… ┆ Mornet        ┆ 84           ┆ true                           │
│ …                               ┆ …             ┆ …            ┆ …                              │
│ Claude HOARAU                   ┆ Hoarau        ┆ 7            ┆ true                           │
│ Égalité Responsa…               ┆               ┆              ┆                                │
│ Sciences Po / fonds CEVIPOF     ┆ Pihouee       ┆ 2017         ┆ true                           │
│ An…                             ┆               ┆              ┆                                │
│ Élie HOARAU                     ┆ Hoarau        ┆ 5            ┆ true                           │
│ Égalité Responsabi…             ┆               ┆              ┆                                │
│ Sciences Po / fonds CEVIPOF     ┆ Virapoullé    ┆ 126          ┆ true                           │
│ EL…                             ┆               ┆              ┆                                │
│ Sciences Po / fonds CEVIPOF     ┆ Vergès        ┆ 33           ┆ true                           │
│ Pa…                             ┆               ┆              ┆                                │
└─────────────────────────────────┴───────────────┴──────────────┴────────────────────────────────┘

In [44]:
df.filter(pl.col("position_nom").is_null())

shape: (130, 48)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ date      ┆ subject   ┆ title     ┆ … ┆ transcrip ┆ titulaire ┆ titulaire ┆ position │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ t_normali ┆ _nom_norm ┆ _nom_is_i ┆ _nom     │
│ str       ┆ datetime[ ┆ str       ┆ str       ┆   ┆ zed       ┆ alized    ┆ n_transcr ┆ ---      │
│           ┆ μs]       ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ipt       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ str       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ bool      ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ EL174_L_1 ┆ 1988-06-0 ┆ Ve Républ ┆ Élections ┆ … ┆ elections ┆ chevalier ┆ false     ┆ null     │
│ 988_06_00 ┆ 5         ┆ ique;Asse ┆ législati ┆   ┆ legislati ┆           ┆           ┆          │
│ 5_01_1_PF ┆ 00:00:00  ┆ mblée     ┆ ves de    ┆   ┆ ves du 5  ┆           ┆           ┆          │
│ _04       ┆           ┆ Nation…   ┆ 1988…     ┆   ┆ ju…       ┆           ┆           ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Ve Républ ┆ Élections ┆ … ┆ departeme ┆ vassalo   ┆ false     ┆ null     │
│ 988_06_00 ┆ 5         ┆ ique;Asse ┆ législati ┆   ┆ nt des    ┆           ┆           ┆          │
│ 6_09_1_PF ┆ 00:00:00  ┆ mblée     ┆ ves de    ┆   ┆ alpes-mar ┆           ┆           ┆          │
│ _02       ┆           ┆ Nation…   ┆ 1988…     ┆   ┆ itime…    ┆           ┆           ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Élections ┆ Élections ┆ … ┆ parti     ┆ non       ┆ false     ┆ null     │
│ 988_06_01 ┆ 5         ┆ législati ┆ législati ┆   ┆ ouvrier   ┆ mentionne ┆           ┆          │
│ 0_01_1_PF ┆ 00:00:00  ┆ ves;Ve    ┆ ves de    ┆   ┆ europeen  ┆           ┆           ┆          │
│ _06       ┆           ┆ Répu…     ┆ 1988…     ┆   ┆ siege :…  ┆           ┆           ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Assemblée ┆ Élections ┆ … ┆ parti     ┆ non       ┆ false     ┆ null     │
│ 988_06_01 ┆ 5         ┆ Nationale ┆ législati ┆   ┆ ouvrier   ┆ mentionne ┆           ┆          │
│ 0_02_1_PF ┆ 00:00:00  ┆ ;France;É ┆ ves de    ┆   ┆ europeen  ┆           ┆           ┆          │
│ _05       ┆           ┆ le…       ┆ 1988…     ┆   ┆ siege :…  ┆           ┆           ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Assemblée ┆ Élections ┆ … ┆ parti     ┆ non       ┆ false     ┆ null     │
│ 988_06_01 ┆ 5         ┆ Nationale ┆ législati ┆   ┆ ouvrier   ┆ mentionne ┆           ┆          │
│ 0_03_1_PF ┆ 00:00:00  ┆ ;Ve       ┆ ves de    ┆   ┆ europeen  ┆           ┆           ┆          │
│ _07       ┆           ┆ Républi…  ┆ 1988…     ┆   ┆ siege :…  ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ EL176_L_1 ┆ 1988-06-1 ┆ France;Él ┆ Élections ┆ … ┆ sciences  ┆ giovanell ┆ false     ┆ null     │
│ 988_06_05 ┆ 2         ┆ ections   ┆ législati ┆   ┆ po /      ┆ i         ┆           ┆          │
│ 6_06_2_PF ┆ 00:00:00  ┆ législati ┆ ves de    ┆   ┆ fonds     ┆           ┆           ┆          │
│ _01       ┆           ┆ ves;…     ┆ 1988…     ┆   ┆ cevipof   ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ma…       ┆           ┆           ┆          │
│ EL176_L_1 ┆ 1988-06-1 ┆ France;Ve ┆ Élections ┆ … ┆ + initiat ┆ guysel    ┆ false     ┆ null     │
│ 988_06_05 ┆ 2         ┆ Républiqu ┆ législati ┆   ┆ ives      ┆           ┆           ┆          │
│ 9_07_2_PF ┆ 00:00:00  ┆ e;Électio ┆ ves de    ┆   ┆ courage = ┆           ┆           ┆          │
│ _01       ┆           ┆ ns…       ┆ 1988…     ┆   ┆ result…   ┆           ┆           ┆          │
│ EL176_L_1 ┆ 1988-06-1 ┆ Ve Républ ┆ Élections ┆ … ┆ sciences  ┆ adevah-po ┆ false     ┆ null     │
│ 988_06_06 ┆ 2         ┆ ique;Élec ┆ législati ┆   ┆ po /      ┆ euf       ┆           ┆          │
│ 3_05_2_PF ┆ 00:00:00  ┆ tions     ┆ ves de    ┆   ┆ fonds     ┆           ┆           ┆          │
│ _01       ┆           ┆ législ…   ┆ 1988…     ┆   ┆ cevipof   ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ re…       ┆           ┆           ┆          │
│ EL177_L_1 ┆ 1988-06-1 ┆ Élections ┆ Élections ┆ … ┆ la france ┆ mocoeur   ┆ false     ┆ null     │
│ 988_06_08 ┆ 2         ┆ législati ┆ législati ┆   ┆ unie      ┆           ┆           ┆          │
│ 7_03_2_PF ┆ 00:00:00  ┆ ves;Assem ┆ ves de    ┆   ┆ avec      ┆           ┆           ┆          │
│ _01       ┆           ┆ bl…       ┆ 1988…     ┆   ┆ sciences  ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ p…        ┆           ┆           ┆          │
│ EL177_L_1 ┆ 1988-06-1 ┆ Élections ┆ Élections ┆ … ┆ sciences  ┆ saint-cri ┆ false     ┆ null     │
│ 988_06_09 ┆ 2         ┆ législati ┆ législati ┆   ┆ po /      ┆ cq        ┆           ┆          │
│ 2_08_2_PF ┆ 00:00:00  ┆ ves;Ve    ┆ ves de    ┆   ┆ fonds     ┆           ┆           ┆          │
│ _02       ┆           ┆ Répu…     ┆ 1988…     ┆   ┆ cevipof   ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ av…       ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘